### ISSUE TITLE
Where do we edit the mongodb uri and the discord token?

### ISSUE THREAD

**Issue by ocowala** [LCProxy/Backend#1]
The title is the question. Also what do we edit the mongodb uri and discord token to?

**Comment by ItsVops** [comment]
me/lcproxy/jb/mongo/MongoManager.java
line 19

me/lcproxy/jb/Discord.java 
line 26

**Comment by ocowala** [comment]
but what do i put with those

**Comment by ItsVops** [comment]
you should probably know how mongodb and discord work before you use this...

**Comment by ChilledLiquid** [comment]
xD
